server:
    port: 9003

spring:
    application:
        name: mcsv-maestros
    config:
        import: ${CONFIG_SERVER} 

    cloud:
        config:
            #nombre base que se busca en el git o repositorio
            name: config-server
